---
sudo: true
language: perl6
perl6:
    - latest
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libgd-dev libgd3
install:
    - rakudobrew build-panda
    - panda --notests installdeps .
